AWSTemplateFormatVersion: 2010-09-09
Description: Elastic Container Registory Repository using Cloudformation

#------------------------
#   PARAMETERS
#------------------------
Parameters:
  repoName: 
    Description: Name for ecr repo 
    Type: String

#------------------------
#   RESOURCES
#------------------------ 
Resources:
  ecrRepo:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${repoName}-repo
      ImageScanningConfiguration: 
        ScanOnPush: true
  myLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupClass: "INFREQUENT_ACCESS"
        LogGroupName: "ambaBeqa"
        RetentionInDays: 14
        Tags: 
          - Key: "app"
            Value: "amba"
          - Key: "side"
            Value: "be"
  MyECSTaskRole:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: "amba-be-qa"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "my-task-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: "*"
